# Generated by Django 5.2.16 on 2026-08-03 16:34

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('plough', 'Plough'), ('seeder', 'Seeder'), ('sprayer', 'Sprayer'), ('irrigation', 'Irrigation'), ('thresher', 'Thresher'), ('cultivator', 'Cultivator'), ('other', 'Other')], default='other', max_length=50)),
                ('purpose', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('hourly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.core.validators.validate_positive_price])),
                ('daily_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.core.validators.validate_positive_price])),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('gps_lat', models.FloatField(blank=True, null=True, validators=[apps.core.validators.validate_latitude])),
                ('gps_lng', models.FloatField(blank=True, null=True, validators=[apps.core.validators.validate_longitude])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.core.validators.validate_positive_price])),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipment.equipment')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(max_length=500)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment')),
            ],
            options={
                'db_table': 'equipment_images',
            },
        ),
    ]
