# Generated by Django 5.2.16 on 2026-08-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipmentbooking',
            table='rentals',
        ),
    ]
