# Generated by Django 6.1.1 on 2026-09-08 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_id', models.CharField(blank=True, default='', help_text='ID of reviewed entity (equipment, product) when reviewee is null.', max_length=64)),
                ('review_type', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('labour', 'Labour'), ('equipment', 'Equipment'), ('product', 'Product')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5.')),
                ('comment', models.TextField(blank=True, default='')),
                ('reviewee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
