# Generated by Django 5.2.16 on 2026-08-03 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('data', models.JSONField(help_text='Raw response payload from OpenWeather API.')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'weather_cache',
                'unique_together': {('lat', 'lng')},
            },
        ),
    ]
