# Generated by Django 5.2.16 on 2026-08-03 16:34

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.core.validators.validate_positive_price])),
                ('wage_type', models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('fixed', 'Fixed')], default='daily', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('gps_lat', models.FloatField(blank=True, null=True, validators=[apps.core.validators.validate_latitude])),
                ('gps_lng', models.FloatField(blank=True, null=True, validators=[apps.core.validators.validate_longitude])),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('num_workers', models.PositiveIntegerField(default=1)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('labour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabourProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text="List of skill strings, e.g. ['ploughing', 'harvesting']")),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[apps.core.validators.validate_positive_price])),
                ('is_available', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labour_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'labour_profiles',
            },
        ),
    ]
